import { mkdir, readFile } from "node:fs/promises";
import path from "node:path";
import { pathExists } from "./git";
import { renderPrompt } from "./prompts";
import type { BuilderResponse, ChangedFile, FileSelection } from "./types";

export function sanitizeForTitle(input: string): string {
  return input
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 64);
}

export function createTimestamp(): string {
  return new Date().toISOString().replace(/[:]/g, "-").replace(/\..+/, "Z");
}

export function inferLanguage(filePath: string): string {
  const ext = path.extname(filePath).toLowerCase();
  const map: Record<string, string> = {
    ".ts": "ts",
    ".tsx": "tsx",
    ".js": "js",
    ".jsx": "jsx",
    ".json": "json",
    ".md": "md",
    ".py": "py",
    ".rb": "rb",
    ".go": "go",
    ".rs": "rs",
    ".swift": "swift",
    ".java": "java",
    ".kt": "kotlin",
    ".kts": "kotlin",
    ".cs": "csharp",
    ".cpp": "cpp",
    ".cc": "cpp",
    ".cxx": "cpp",
    ".c": "c",
    ".h": "c",
    ".hpp": "cpp",
    ".php": "php",
    ".sh": "bash",
    ".bash": "bash",
    ".zsh": "bash",
    ".yml": "yaml",
    ".yaml": "yaml",
    ".toml": "toml",
    ".xml": "xml",
    ".html": "html",
    ".css": "css",
    ".sql": "sql"
  };
  return map[ext] ?? "";
}

export function renderChangedFiles(changedFiles: ChangedFile[]): string {
  if (changedFiles.length === 0) {
    return "(none)";
  }

  return changedFiles
    .map((file) =>
      file.previousPath
        ? `- [${file.status}] ${file.previousPath} -> ${file.path}`
        : `- [${file.status}] ${file.path}`
    )
    .join("\n");
}

export function renderReviewInstructions(): string {
  return renderPrompt("final-review");
}

export function approximateTokens(text: string): number {
  return Math.ceil(text.length / 4);
}

export async function renderSelectedFileSection(repoRoot: string, selection: FileSelection): Promise<string> {
  const absolute = path.join(repoRoot, selection.path);
  const contents = await readFile(absolute, "utf8");
  const language = inferLanguage(selection.path);

  if (selection.include_mode === "full") {
    return `### ${selection.path}
Reason: ${selection.rationale}
Mode: full

\`\`\`${language}
${contents}
\`\`\`
`;
  }

  const lines = contents.split("\n");
  const blocks: string[] = [];
  for (const range of selection.ranges) {
    const start = Math.max(1, range.start_line);
    const end = Math.min(lines.length, range.end_line);
    const body = lines.slice(start - 1, end).join("\n");
    blocks.push(
      `Range ${start}-${end}: ${range.description}

\`\`\`${language}
${body}
\`\`\``
    );
  }

  return `### ${selection.path}
Reason: ${selection.rationale}
Mode: slice

${blocks.join("\n\n")}
`;
}

export async function buildMarkdownBundle(input: {
  repoRoot: string;
  title: string;
  compareDescription: string;
  branch: string;
  statusText: string;
  recentLog: string;
  changedFiles: ChangedFile[];
  patch: string;
  builder: BuilderResponse;
  selections: FileSelection[];
}): Promise<string> {
  const fileSections: string[] = [];
  for (const selection of input.selections) {
    const absolute = path.join(input.repoRoot, selection.path);
    if (!(await pathExists(absolute))) {
      continue;
    }
    fileSections.push(await renderSelectedFileSection(input.repoRoot, selection));
  }

  const metadata = [
    `- Repository: ${path.basename(input.repoRoot)}`,
    `- Repository root: ${input.repoRoot}`,
    `- Current branch: ${input.branch || "(detached or unborn)"}`,
    `- Comparison scope: ${input.compareDescription}`,
    `- Builder summary: ${input.builder.summary}`
  ].join("\n");

  const focusBlock =
    input.builder.review_focus.length > 0
      ? input.builder.review_focus.map((line) => `- ${line}`).join("\n")
      : "(none)";

  const notesBlock =
    input.builder.notes_for_final_reviewer.length > 0
      ? input.builder.notes_for_final_reviewer.map((line) => `- ${line}`).join("\n")
      : "(none)";

  const warningsBlock =
    input.builder.warnings.length > 0
      ? input.builder.warnings.map((line) => `- ${line}`).join("\n")
      : "(none)";

  return `# ${input.title}

This bundle was generated by a local Bun script for ChatGPT 5.4 Pro.

## Review Instructions

${renderReviewInstructions()}

## Bundle Metadata

${metadata}

## Builder Focus

${focusBlock}

## Notes For Final Reviewer

${notesBlock}

## Builder Warnings / Uncertainty

${warningsBlock}

## Current Git Status

\`\`\`text
${input.statusText || "(empty)"}
\`\`\`

## Changed Files

${renderChangedFiles(input.changedFiles)}

## Recent Git History

\`\`\`text
${input.recentLog || "(no commits available)"}
\`\`\`

## Git Diff

\`\`\`diff
${input.patch || "(no patch content available for this scope)"}
\`\`\`

## Selected Context Files

${fileSections.join("\n")}
`;
}

export async function ensureOutputPath(repoRoot: string, requested?: string, title?: string): Promise<string> {
  if (requested) {
    const absolute = path.isAbsolute(requested) ? requested : path.join(repoRoot, requested);
    await mkdir(path.dirname(absolute), { recursive: true });
    return absolute;
  }

  const outputDir = path.join(repoRoot, ".review-export");
  await mkdir(outputDir, { recursive: true });
  const stamp = createTimestamp();
  const name = sanitizeForTitle(title ?? "review-bundle") || "review-bundle";
  return path.join(outputDir, `${stamp}-${name}.md`);
}
